### ISSUE TITLE
Citra crashes on launch of a game

### ISSUE THREAD

**Issue by Spidy123222** [rinsuki/citra#11]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

https://github.com/rinsuki/citra/actions/runs/4775303138

### Description of Issue

Currently the app crashes on booting of a game and have tried with jit and without jit.

### Expected Behavior

Shouldn’t crash

### Reproduction Steps

Run any game and watch it as it crashes

### Log File

https://cdn.discordapp.com/attachments/1098146488305066064/1100930918711033996/citra_ios-2023-04-26-163904.ips

### System Configuration

CPU: A11 (iPhone 8 plus)
GPU/Driver: A11
RAM: 3gb
OS: iOS 16.4.1

**Comment by rinsuki** [comment]
A12 or later is required.
