### ISSUE TITLE
how it can run ios13?

### ISSUE THREAD

**Issue by hentaisama** [rinsuki/citra#9]
### Issue

my device version is ios13.4.1,i want to ask how can it run on it? i don't want to upgrade my device.

**Comment by rinsuki** [comment]
I tried, but It would be hard to support.

these are reasons:
* Citra (not iOS port) depending to some libcpp's functionallity that not available in iOS 13.x.
* citra_ios depending to API that returns "current" GCController, but it is not available in iOS 13.x.

**Comment by hentaisama** [comment]
Thank you very much , now I have update ios 16.xxxxxxxxxd

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2023年5月2日 7:50
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [rinsuki/citra] how it can run ios13? (Issue #9)


I tried, but It would be hard to support.

these are reasons:

  *   Citra (not iOS port) depending to some libcpp's functionallity that not available in iOS 13.x.
  *   citra_ios depending to API that returns "current" GCController, but it is not available in iOS 13.x.

―

**Comment by hentaisama** [comment]
Thank you! Now I have update ios16

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2023年5月2日 7:50
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [rinsuki/citra] how it can run ios13? (Issue #9)


I tried, but It would be hard to support.

these are reasons:

  *   Citra (not iOS port) depending to some libcpp's functionallity that not available in iOS 13.x.
  *   citra_ios depending to API that returns "current" GCController, but it is not available in iOS 13.x.

―
